baseurl = "https://retroverse.github.io\\Obtuse-Triangle\\site\\"
title = "The Obtuse Triangle"
languageCode = "en-us"
publishDir = "../site"
canonifyurls = true

MetaDataFormat = "toml"
theme = "slender"
paginate = 3
PaginatePath = "/"

[author]
    name = "Ewan Breakey"

[permalinks]

    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/article/:title/"

[params]

    # Change the color scheme of Slender.
    # See above for preview and list of color schemes.
    colorscheme = "white"

    # Tagline; HTML accepted here. Keep it concise.
    tagline = ""

    # Footer; Markdown accepted here.
    footer = "Copyright 2015 &copy; Ewan Breakey"

    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # of the markdown file.
    description = "Programming Blog of Ewan Breakey"
    keywords = "programming, tooling, tdos, democracy-of-sheep"

    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
    # Remove, comment, or leave blank any field to leave them out.
    email = "mailto:sheeplovedemocracy@gmail.com"
    github = "github.com/retroverse"
    twitter = "twitter.com/retr0verse"

[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "home"
    url        = "/"
    weight     = 0
